[package]
name = "teach-rust-00-intro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = { git = "https://github.com/sycamore-rs/sycamore" }
log = "0.4.17"
wasm-logger = "0.2.0"